Added .clang-format configuration and fixed all the formatting
Clang format file source: https://github.com/torvalds/linux/blob/master/.clang-format
Replace checkpatch.pl script in pre-commit hook with clang-format
Removed .clang-format file from gitignore

FSF Edits:

Updated for one more patch

Removed src/FSAL/FSAL_GPFS/include/gpfs.h from consideration as it is a
direct copy from the GPFS source code with the addition of the SPDX header
and a comment pointing out it should not be changed. This happens to revert
some spelling corrections that were made in misunderstanding and restores
the file to the original source with these modifications.

Change-Id: Ic7b9bf01c813a315a81b4734e9abe7b8e9fcf90a
Signed-off-by: Lior Suliman <liorsu@gmail.com>
Signed-off-by: Frank Filz <ffilzlnx@mindspring.com>

diff --git a/src/scripts/git_hooks/pre-commit b/src/scripts/git_hooks/pre-commit
--- a/src/scripts/git_hooks/pre-commit
+++ b/src/scripts/git_hooks/pre-commit
@@ -1,33 +1,55 @@
 #!/bin/bash
 # Ganesha pre-commit hook
 #
-# 1. Run checkpatch on the commit
+# 1. Run clang-format on the commit
 # 2. Check to see if a submodule is not being updated
 
-
 # define colors for use in output
+red='\033[0;31m'
 green='\033[0;32m'
 no_color='\033[0m'
 grey='\033[0;90m'
 
+#####################
+# Clang-Format Hook
+#####################
 
-if git rev-parse --verify HEAD 2>/dev/null >/dev/null
-then
-	against=HEAD
-else
-	# Initial commit: diff against an empty tree object
-	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
-fi
+function handle_unformatted_file() {
+    set -u
+    # If a rebase is in progress just show warning.
+    git rebase --show-current-patch 1> /dev/null 2> /dev/null
+    if [[ $? == 0 ]]; then
+        echo "[git-pre-commit warning] clang-format found formatting missing in commit."
+        echo "[git-pre-commit warning] In rebase so just printing the warning without failing the commit."
+    else
+        echo -e "${red}[git-pre-commit error]${no_color} clang-format found formatting missing in commit. commit aborted."
+        exit 1
+    fi
+}
 
-topdir=$(git rev-parse --show-toplevel)
-git diff --cached  $against | $topdir/src/scripts/checkpatch.pl \
-	      --no-signoff -q -
-if [ $? != 0 ]; then
-	exit 1
-fi
+function check_staged_files() {
+    set -u
+    local test_command="(cd src; clang-format -style=file --dry-run --Werror -)"
+    local retval=0
+    for file in $(git diff --cached --name-only --diff-filter=d -- 'src/*.c' 'src/*.h' 'src/*.cpp' 'src/*.hpp' 'src/*.cc')
+    do
+        git show :${file} | eval "${test_command}"
+        if [[ $? != 0 ]]; then
+            echo "ERROR: Staged file ${file} is not formatted correctly, please use clang-format to format it"
+            retval=1
+        fi
+    done
+    if [[ ${retval} != 0 ]]; then
+       handle_unformatted_file
+    fi
+}
 
+check_staged_files
+
+###############################################################
 # Check whether any submodule is about to be updated with the
 # commit. Ask the user for confirmation.
+###############################################################
 
 echo -e "Checking submodules ${grey}(pre-commit hook)${no_color} "
 
